/**
 * generate-og-all.mjs
 *
 * Generates share images for EVERY suburb (858+), not just the worst-20 subset
 * that the main build:og step covers. Run this separately after a full build:
 *
 *   npx tsx scripts/generate-og-all.mjs
 *
 * Features:
 *  - Skips images that already exist (safe to re-run / resume).
 *  - Processes in batches of 8 to limit peak memory.
 *  - Writes og-all-manifest.json alongside og-manifest.json so tooling
 *    can verify full coverage independently of the compliance gate.
 *
 * Does NOT re-run the compliance gate (that is the main build:og job's
 * responsibility for the worst-20 pages that appear in social previews).
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import satori from 'satori';
import { Resvg } from '@resvg/resvg-js';
import { ogTemplate, OG_WIDTH, OG_HEIGHT } from './og-template.mjs';
import { site } from '../src/config/site.ts';
import { BAND_COLORS } from '../src/lib/scoring.ts';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const CLIENT_DIR = path.resolve(__dirname, '../dist/client');
const OG_DIR = path.join(CLIENT_DIR, 'og');
const GENERATED = path.resolve(__dirname, '../src/data/generated');
const SUBURBS_DIR = path.resolve(__dirname, '../public/data/suburbs');

// ── guard: dist/client must exist (run after a build) ──────────────────────
if (!fs.existsSync(CLIENT_DIR)) {
    console.error('[generate-og-all] dist/client not found. Run `npm run build` first.');
    process.exit(1);
}

fs.mkdirSync(OG_DIR, { recursive: true });

const manifest = JSON.parse(fs.readFileSync(path.join(GENERATED, 'manifest.json'), 'utf8'));
const suburbIndex = JSON.parse(fs.readFileSync(path.join(GENERATED, 'suburb-index.json'), 'utf8'));
const siteLabel = new URL(site.origin).host;

// ── logo ────────────────────────────────────────────────────────────────────
const logoSvgPath = path.resolve(__dirname, '../public/solo-mono-white.svg');
const logoDataUrl = `data:image/svg+xml;base64,${fs.readFileSync(logoSvgPath).toString('base64')}`;

// ── fonts ───────────────────────────────────────────────────────────────────
const fontFile = (pkg, file) =>
    fs.readFileSync(path.resolve(__dirname, `../node_modules/@fontsource/${pkg}/files/${file}`));

const fonts = [
    { name: 'Barlow', data: fontFile('barlow', 'barlow-latin-400-normal.woff'), weight: 400, style: 'normal' },
    { name: 'Barlow', data: fontFile('barlow', 'barlow-latin-600-normal.woff'), weight: 600, style: 'normal' },
    { name: 'Barlow Condensed', data: fontFile('barlow-condensed', 'barlow-condensed-latin-900-normal.woff'), weight: 900, style: 'normal' },
    { name: 'Space Mono', data: fontFile('space-mono', 'space-mono-latin-700-normal.woff'), weight: 700, style: 'normal' },
];

// ── render helper ───────────────────────────────────────────────────────────
async function renderPng(props, outPath) {
    const tree = ogTemplate({
        ...props,
        expectedAuthLine: site.authorisationLine,
        authLine: site.authorisationLine,
        fixture: manifest.fixture,
        siteLabel,
        logoDataUrl,
    });
    const svg = await satori(tree, { width: OG_WIDTH, height: OG_HEIGHT, fonts });
    const png = new Resvg(svg, { fitTo: { mode: 'width', value: OG_WIDTH } }).render().asPng();
    // Recreate dir defensively: a cleanup process may have removed it mid-run.
    fs.mkdirSync(path.dirname(outPath), { recursive: true });
    fs.writeFileSync(outPath, png);
}

// ── build job list (all suburbs, skip existing) ──────────────────────────────
const jobs = [];

for (const s of suburbIndex.suburbs) {
    const outFile = `${s.slug}.png`;
    const outPath = path.join(OG_DIR, outFile);

    // Skip suburbs that already have an image (generated by build:og or a
    // previous run of this script).
    if (fs.existsSync(outPath)) continue;

    const detailPath = path.resolve(SUBURBS_DIR, `${s.slug}.json`);
    if (!fs.existsSync(detailPath)) continue;

    const detail = JSON.parse(fs.readFileSync(detailPath, 'utf8'));
    jobs.push({
        file: outFile,
        outPath,
        slug: s.slug,
        props: {
            heading: detail.name,
            score: detail.score,
            scoreColor: BAND_COLORS[detail.band],
            verdict: detail.verdict,
        },
    });
}

if (jobs.length === 0) {
    console.log('[generate-og-all] all suburb images already exist - nothing to do.');
    process.exit(0);
}

console.log(`[generate-og-all] generating ${jobs.length} suburb image(s)…`);

// ── render in batches of 8 ──────────────────────────────────────────────────
const BATCH = 8;
const entries = [];
let done = 0;

for (let i = 0; i < jobs.length; i += BATCH) {
    await Promise.all(
        jobs.slice(i, i + BATCH).map(async job => {
            try {
                await renderPng(job.props, job.outPath);
                entries.push({ file: job.file, slug: job.slug });
                done++;
            } catch (err) {
                console.error(`[generate-og-all] failed: ${job.file} - ${err.message}`);
            }
        }),
    );
    // Progress every 10 batches
    if (Math.floor(i / BATCH) % 10 === 0) {
        console.log(`[generate-og-all] ${done}/${jobs.length} done…`);
    }
}

// ── write manifest ───────────────────────────────────────────────────────────
fs.mkdirSync(OG_DIR, { recursive: true });
fs.writeFileSync(
    path.join(OG_DIR, 'og-all-manifest.json'),
    JSON.stringify({ generatedAt: new Date().toISOString(), total: entries.length, images: entries }, null, 2),
);

const failures = jobs.length - entries.length;
console.log(`[generate-og-all] wrote ${entries.length} image(s) to ${OG_DIR}${failures ? ` (${failures} failed)` : ''}`);
if (failures > 0) process.exit(1);
